-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "closingAwayLine" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "closingTotalLine" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LiveGameLine" ALTER COLUMN "awayLine" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalLine" SET DATA TYPE DOUBLE PRECISION;
